// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.1
// source: control_net/control_net.proto

package control_net

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetR401Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetR401Request) Reset() {
	*x = GetR401Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetR401Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetR401Request) ProtoMessage() {}

func (x *GetR401Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetR401Request.ProtoReflect.Descriptor instead.
func (*GetR401Request) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{0}
}

type GetR401Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *VarReplyData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetR401Reply) Reset() {
	*x = GetR401Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetR401Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetR401Reply) ProtoMessage() {}

func (x *GetR401Reply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetR401Reply.ProtoReflect.Descriptor instead.
func (*GetR401Reply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{1}
}

func (x *GetR401Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetR401Reply) GetData() *VarReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type R401Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *R401Info) Reset() {
	*x = R401Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R401Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R401Info) ProtoMessage() {}

func (x *R401Info) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R401Info.ProtoReflect.Descriptor instead.
func (*R401Info) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{2}
}

type GetOperationVarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOperationVarsRequest) Reset() {
	*x = GetOperationVarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOperationVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationVarsRequest) ProtoMessage() {}

func (x *GetOperationVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationVarsRequest.ProtoReflect.Descriptor instead.
func (*GetOperationVarsRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{3}
}

type GetOperationVarsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *VarReplyData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOperationVarsReply) Reset() {
	*x = GetOperationVarsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOperationVarsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationVarsReply) ProtoMessage() {}

func (x *GetOperationVarsReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationVarsReply.ProtoReflect.Descriptor instead.
func (*GetOperationVarsReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{4}
}

func (x *GetOperationVarsReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOperationVarsReply) GetData() *VarReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetReactorPerformanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReactorPerformanceRequest) Reset() {
	*x = GetReactorPerformanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactorPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactorPerformanceRequest) ProtoMessage() {}

func (x *GetReactorPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactorPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetReactorPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{5}
}

type GetReactorPerformanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *VarReplyData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetReactorPerformanceReply) Reset() {
	*x = GetReactorPerformanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactorPerformanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactorPerformanceReply) ProtoMessage() {}

func (x *GetReactorPerformanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactorPerformanceReply.ProtoReflect.Descriptor instead.
func (*GetReactorPerformanceReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{6}
}

func (x *GetReactorPerformanceReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReactorPerformanceReply) GetData() *VarReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetR401APCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SetValue float64 `protobuf:"fixed64,2,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
}

func (x *SetR401APCRequest) Reset() {
	*x = SetR401APCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetR401APCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetR401APCRequest) ProtoMessage() {}

func (x *SetR401APCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetR401APCRequest.ProtoReflect.Descriptor instead.
func (*SetR401APCRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{7}
}

func (x *SetR401APCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetR401APCRequest) GetSetValue() float64 {
	if x != nil {
		return x.SetValue
	}
	return 0
}

type SetR401APCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SetR401APCReply) Reset() {
	*x = SetR401APCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetR401APCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetR401APCReply) ProtoMessage() {}

func (x *SetR401APCReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetR401APCReply.ProtoReflect.Descriptor instead.
func (*SetR401APCReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{8}
}

func (x *SetR401APCReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type SetOperationVarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RcyMaterialFlow     string `protobuf:"bytes,1,opt,name=rcy_material_flow,json=rcyMaterialFlow,proto3" json:"rcy_material_flow,omitempty"`
	CHRation            string `protobuf:"bytes,2,opt,name=c_h_ration,json=cHRation,proto3" json:"c_h_ration,omitempty"`
	EntranceTemperature string `protobuf:"bytes,3,opt,name=entrance_temperature,json=entranceTemperature,proto3" json:"entrance_temperature,omitempty"`
	HFlow               string `protobuf:"bytes,4,opt,name=h_flow,json=hFlow,proto3" json:"h_flow,omitempty"`
}

func (x *SetOperationVarsRequest) Reset() {
	*x = SetOperationVarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOperationVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperationVarsRequest) ProtoMessage() {}

func (x *SetOperationVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperationVarsRequest.ProtoReflect.Descriptor instead.
func (*SetOperationVarsRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{9}
}

func (x *SetOperationVarsRequest) GetRcyMaterialFlow() string {
	if x != nil {
		return x.RcyMaterialFlow
	}
	return ""
}

func (x *SetOperationVarsRequest) GetCHRation() string {
	if x != nil {
		return x.CHRation
	}
	return ""
}

func (x *SetOperationVarsRequest) GetEntranceTemperature() string {
	if x != nil {
		return x.EntranceTemperature
	}
	return ""
}

func (x *SetOperationVarsRequest) GetHFlow() string {
	if x != nil {
		return x.HFlow
	}
	return ""
}

type SetOperationVarsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetOperationVarsReply) Reset() {
	*x = SetOperationVarsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOperationVarsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperationVarsReply) ProtoMessage() {}

func (x *SetOperationVarsReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperationVarsReply.ProtoReflect.Descriptor instead.
func (*SetOperationVarsReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{10}
}

type ConfirmReactorPerfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmReactorPerfRequest) Reset() {
	*x = ConfirmReactorPerfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReactorPerfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReactorPerfRequest) ProtoMessage() {}

func (x *ConfirmReactorPerfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReactorPerfRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReactorPerfRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{11}
}

type ConfirmReactorPerfReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmReactorPerfReply) Reset() {
	*x = ConfirmReactorPerfReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReactorPerfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReactorPerfReply) ProtoMessage() {}

func (x *ConfirmReactorPerfReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReactorPerfReply.ProtoReflect.Descriptor instead.
func (*ConfirmReactorPerfReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{12}
}

type GetReactorPerfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReactorPerfRequest) Reset() {
	*x = GetReactorPerfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactorPerfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactorPerfRequest) ProtoMessage() {}

func (x *GetReactorPerfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactorPerfRequest.ProtoReflect.Descriptor instead.
func (*GetReactorPerfRequest) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{13}
}

type GetReactorPerfReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MAPD string `protobuf:"bytes,1,opt,name=MAPD,proto3" json:"MAPD,omitempty"`
	C3H6 string `protobuf:"bytes,2,opt,name=c3h6,proto3" json:"c3h6,omitempty"`
	C3H8 string `protobuf:"bytes,3,opt,name=c3h8,proto3" json:"c3h8,omitempty"`
}

func (x *GetReactorPerfReply) Reset() {
	*x = GetReactorPerfReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactorPerfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactorPerfReply) ProtoMessage() {}

func (x *GetReactorPerfReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactorPerfReply.ProtoReflect.Descriptor instead.
func (*GetReactorPerfReply) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{14}
}

func (x *GetReactorPerfReply) GetMAPD() string {
	if x != nil {
		return x.MAPD
	}
	return ""
}

func (x *GetReactorPerfReply) GetC3H6() string {
	if x != nil {
		return x.C3H6
	}
	return ""
}

func (x *GetReactorPerfReply) GetC3H8() string {
	if x != nil {
		return x.C3H8
	}
	return ""
}

type VarReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*VarDetail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *VarReplyData) Reset() {
	*x = VarReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarReplyData) ProtoMessage() {}

func (x *VarReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarReplyData.ProtoReflect.Descriptor instead.
func (*VarReplyData) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{15}
}

func (x *VarReplyData) GetList() []*VarDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type VarDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc         string  `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	RealValue    float64 `protobuf:"fixed64,3,opt,name=real_value,json=realValue,proto3" json:"real_value,omitempty"`
	SetValue     float64 `protobuf:"fixed64,4,opt,name=set_value,json=setValue,proto3" json:"set_value,omitempty"`
	LowLimit     float64 `protobuf:"fixed64,5,opt,name=low_limit,json=lowLimit,proto3" json:"low_limit,omitempty"`
	HighLimit    float64 `protobuf:"fixed64,6,opt,name=high_limit,json=highLimit,proto3" json:"high_limit,omitempty"`
	Unit         string  `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	EditAble     bool    `protobuf:"varint,8,opt,name=edit_able,json=editAble,proto3" json:"edit_able,omitempty"`
	IsSwitch     bool    `protobuf:"varint,9,opt,name=is_switch,json=isSwitch,proto3" json:"is_switch,omitempty"`
	SwitchStatus bool    `protobuf:"varint,10,opt,name=switch_status,json=switchStatus,proto3" json:"switch_status,omitempty"`
}

func (x *VarDetail) Reset() {
	*x = VarDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_net_control_net_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarDetail) ProtoMessage() {}

func (x *VarDetail) ProtoReflect() protoreflect.Message {
	mi := &file_control_net_control_net_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarDetail.ProtoReflect.Descriptor instead.
func (*VarDetail) Descriptor() ([]byte, []int) {
	return file_control_net_control_net_proto_rawDescGZIP(), []int{16}
}

func (x *VarDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VarDetail) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *VarDetail) GetRealValue() float64 {
	if x != nil {
		return x.RealValue
	}
	return 0
}

func (x *VarDetail) GetSetValue() float64 {
	if x != nil {
		return x.SetValue
	}
	return 0
}

func (x *VarDetail) GetLowLimit() float64 {
	if x != nil {
		return x.LowLimit
	}
	return 0
}

func (x *VarDetail) GetHighLimit() float64 {
	if x != nil {
		return x.HighLimit
	}
	return 0
}

func (x *VarDetail) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *VarDetail) GetEditAble() bool {
	if x != nil {
		return x.EditAble
	}
	return false
}

func (x *VarDetail) GetIsSwitch() bool {
	if x != nil {
		return x.IsSwitch
	}
	return false
}

func (x *VarDetail) GetSwitchStatus() bool {
	if x != nil {
		return x.SwitchStatus
	}
	return false
}

var File_control_net_control_net_proto protoreflect.FileDescriptor

var file_control_net_control_net_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x34, 0x30, 0x31, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61,
	0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x56, 0x61, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e,
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x63,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74,
	0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x41, 0x50,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x65, 0x74,
	0x52, 0x34, 0x30, 0x31, 0x41, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xad, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11,
	0x72, 0x63, 0x79, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x63, 0x79, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x5f, 0x68, 0x5f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x48,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x14, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65,
	0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x5f, 0x66,
	0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x46, 0x6c, 0x6f, 0x77,
	0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x61, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50,
	0x65, 0x72, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x41, 0x50, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4d, 0x41, 0x50, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x33, 0x68, 0x36, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x33, 0x68, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x33, 0x68,
	0x38, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x33, 0x68, 0x38, 0x22, 0x3e, 0x0a,
	0x0c, 0x56, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x56, 0x61,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x9e, 0x02,
	0x0a, 0x09, 0x56, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x68, 0x69, 0x67, 0x68, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x68, 0x69, 0x67, 0x68, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x65, 0x64, 0x69, 0x74, 0x41, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xdd,
	0x07, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4e, 0x65, 0x74, 0x12, 0x6f, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x41, 0x50, 0x43, 0x12, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x34, 0x30, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x2f, 0x72, 0x34, 0x30, 0x31, 0x2d, 0x61, 0x70, 0x63, 0x12, 0x8d,
	0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x61, 0x72, 0x73, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x56, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f,
	0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x2f,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x76, 0x61, 0x72, 0x73, 0x12, 0xa1,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x12, 0x24, 0x2f, 0x63,
	0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x2f, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x78, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x41, 0x50, 0x43,
	0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e,
	0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x41, 0x50, 0x43, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x34, 0x30, 0x31, 0x41, 0x50,
	0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01,
	0x2a, 0x22, 0x19, 0x2f, 0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d,
	0x6e, 0x65, 0x74, 0x2f, 0x72, 0x34, 0x30, 0x31, 0x2d, 0x61, 0x70, 0x63, 0x12, 0x90, 0x01, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72,
	0x73, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65,
	0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x3a, 0x01, 0x2a, 0x22, 0x1f,
	0x2f, 0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x6e, 0x65, 0x74,
	0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x76, 0x61, 0x72, 0x73, 0x12,
	0x94, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x22, 0x3a, 0x01, 0x2a, 0x22, 0x1d, 0x2f, 0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x2f, 0x72, 0x65, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2d, 0x70, 0x65, 0x72, 0x66, 0x12, 0x85, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65, 0x72, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x6e, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x65,
	0x72, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12,
	0x1d, 0x2f, 0x63, 0x33, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x6e, 0x65,
	0x74, 0x2f, 0x72, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x70, 0x65, 0x72, 0x66, 0x42, 0x3c,
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x01, 0x5a, 0x23, 0x63, 0x33, 0x68, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_net_control_net_proto_rawDescOnce sync.Once
	file_control_net_control_net_proto_rawDescData = file_control_net_control_net_proto_rawDesc
)

func file_control_net_control_net_proto_rawDescGZIP() []byte {
	file_control_net_control_net_proto_rawDescOnce.Do(func() {
		file_control_net_control_net_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_net_control_net_proto_rawDescData)
	})
	return file_control_net_control_net_proto_rawDescData
}

var file_control_net_control_net_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_control_net_control_net_proto_goTypes = []interface{}{
	(*GetR401Request)(nil),               // 0: api.control_net.GetR401Request
	(*GetR401Reply)(nil),                 // 1: api.control_net.GetR401Reply
	(*R401Info)(nil),                     // 2: api.control_net.R401Info
	(*GetOperationVarsRequest)(nil),      // 3: api.control_net.GetOperationVarsRequest
	(*GetOperationVarsReply)(nil),        // 4: api.control_net.GetOperationVarsReply
	(*GetReactorPerformanceRequest)(nil), // 5: api.control_net.GetReactorPerformanceRequest
	(*GetReactorPerformanceReply)(nil),   // 6: api.control_net.GetReactorPerformanceReply
	(*SetR401APCRequest)(nil),            // 7: api.control_net.SetR401APCRequest
	(*SetR401APCReply)(nil),              // 8: api.control_net.SetR401APCReply
	(*SetOperationVarsRequest)(nil),      // 9: api.control_net.SetOperationVarsRequest
	(*SetOperationVarsReply)(nil),        // 10: api.control_net.SetOperationVarsReply
	(*ConfirmReactorPerfRequest)(nil),    // 11: api.control_net.ConfirmReactorPerfRequest
	(*ConfirmReactorPerfReply)(nil),      // 12: api.control_net.ConfirmReactorPerfReply
	(*GetReactorPerfRequest)(nil),        // 13: api.control_net.GetReactorPerfRequest
	(*GetReactorPerfReply)(nil),          // 14: api.control_net.GetReactorPerfReply
	(*VarReplyData)(nil),                 // 15: api.control_net.VarReplyData
	(*VarDetail)(nil),                    // 16: api.control_net.VarDetail
}
var file_control_net_control_net_proto_depIdxs = []int32{
	15, // 0: api.control_net.GetR401Reply.data:type_name -> api.control_net.VarReplyData
	15, // 1: api.control_net.GetOperationVarsReply.data:type_name -> api.control_net.VarReplyData
	15, // 2: api.control_net.GetReactorPerformanceReply.data:type_name -> api.control_net.VarReplyData
	16, // 3: api.control_net.VarReplyData.list:type_name -> api.control_net.VarDetail
	0,  // 4: api.control_net.ControlNet.GetR401APC:input_type -> api.control_net.GetR401Request
	3,  // 5: api.control_net.ControlNet.GetOperationVars:input_type -> api.control_net.GetOperationVarsRequest
	5,  // 6: api.control_net.ControlNet.GetReactorPerformance:input_type -> api.control_net.GetReactorPerformanceRequest
	7,  // 7: api.control_net.ControlNet.SetR401APC:input_type -> api.control_net.SetR401APCRequest
	9,  // 8: api.control_net.ControlNet.SetOperationVars:input_type -> api.control_net.SetOperationVarsRequest
	11, // 9: api.control_net.ControlNet.ConfirmReactorPerf:input_type -> api.control_net.ConfirmReactorPerfRequest
	13, // 10: api.control_net.ControlNet.GetReactorPerf:input_type -> api.control_net.GetReactorPerfRequest
	1,  // 11: api.control_net.ControlNet.GetR401APC:output_type -> api.control_net.GetR401Reply
	4,  // 12: api.control_net.ControlNet.GetOperationVars:output_type -> api.control_net.GetOperationVarsReply
	6,  // 13: api.control_net.ControlNet.GetReactorPerformance:output_type -> api.control_net.GetReactorPerformanceReply
	8,  // 14: api.control_net.ControlNet.SetR401APC:output_type -> api.control_net.SetR401APCReply
	10, // 15: api.control_net.ControlNet.SetOperationVars:output_type -> api.control_net.SetOperationVarsReply
	12, // 16: api.control_net.ControlNet.ConfirmReactorPerf:output_type -> api.control_net.ConfirmReactorPerfReply
	14, // 17: api.control_net.ControlNet.GetReactorPerf:output_type -> api.control_net.GetReactorPerfReply
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_control_net_control_net_proto_init() }
func file_control_net_control_net_proto_init() {
	if File_control_net_control_net_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_net_control_net_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetR401Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetR401Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R401Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOperationVarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOperationVarsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactorPerformanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactorPerformanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetR401APCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetR401APCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOperationVarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOperationVarsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReactorPerfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReactorPerfReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactorPerfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactorPerfReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_net_control_net_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_net_control_net_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_net_control_net_proto_goTypes,
		DependencyIndexes: file_control_net_control_net_proto_depIdxs,
		MessageInfos:      file_control_net_control_net_proto_msgTypes,
	}.Build()
	File_control_net_control_net_proto = out.File
	file_control_net_control_net_proto_rawDesc = nil
	file_control_net_control_net_proto_goTypes = nil
	file_control_net_control_net_proto_depIdxs = nil
}
