// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"c3h/internal/biz"
	"c3h/internal/conf"
	"c3h/internal/data"
	"c3h/internal/job"
	"c3h/internal/server"
	"c3h/internal/service"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confData *conf.Data, logger log.Logger) (*C3h, func(), error) {
	db := data.NewDB(confData, logger)
	auditLogRepo := data.NewAuditLogRepo(db, logger)
	auditLogUsecase := biz.NewAuditLogUsecase(auditLogRepo, logger)
	controlNetService := service.NewControlNetService()
	productNetRepo := data.NewProductNetRepo(logger)
	productNetUsecase := biz.NewProductNetUsecase(productNetRepo, logger)
	productNetService := service.NewProductNetService(productNetUsecase, logger)
	cache := data.NewCache(confData)
	moduleRelationRepo := data.NewModuleRelationRepo(db, cache, logger)
	dataInfoRepo := data.NewDataInfoRepo(db, cache, logger)
	r401SRepo := data.NewR401SRepo(db, moduleRelationRepo, dataInfoRepo, logger)
	r401SUsecase := biz.NewR401SUsecase(r401SRepo, dataInfoRepo, logger)
	r401SService := service.NewR401SService(r401SUsecase, logger)
	httpServer := server.NewHTTPServer(bootstrap, auditLogUsecase, controlNetService, productNetService, r401SService, logger)
	cronLogger := job.NewCronLogger(logger)
	collectRepo := data.NewCollectorRepo(logger)
	collectUsecase := biz.NewCollectUsecase(logger, collectRepo, moduleRelationRepo, dataInfoRepo)
	collectJob := job.NewCollectJob(bootstrap, logger, collectUsecase, auditLogUsecase)
	cron := job.NewCron(cronLogger, collectJob)
	c3h := newApp(logger, httpServer, cron)
	return c3h, func() {
	}, nil
}
