// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: product_net/product_net.proto

package product_net

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductNet_GetSwitchInfo_FullMethodName      = "/api.product_net.ProductNet/GetSwitchInfo"
	ProductNet_GetControlVars_FullMethodName     = "/api.product_net.ProductNet/GetControlVars"
	ProductNet_GetControlledVars_FullMethodName  = "/api.product_net.ProductNet/GetControlledVars"
	ProductNet_GetConfoundingVars_FullMethodName = "/api.product_net.ProductNet/GetConfoundingVars"
	ProductNet_GetCatalyst_FullMethodName        = "/api.product_net.ProductNet/GetCatalyst"
)

// ProductNetClient is the client API for ProductNet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductNetClient interface {
	GetSwitchInfo(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchReply, error)
	GetControlVars(ctx context.Context, in *ControlVarRequest, opts ...grpc.CallOption) (*ControlVarReply, error)
	GetControlledVars(ctx context.Context, in *ControlledVarRequest, opts ...grpc.CallOption) (*ControlledVarReply, error)
	GetConfoundingVars(ctx context.Context, in *ConfoundingVarRequest, opts ...grpc.CallOption) (*ConfoundingVarReply, error)
	GetCatalyst(ctx context.Context, in *CatalystRequest, opts ...grpc.CallOption) (*CatalystReply, error)
}

type productNetClient struct {
	cc grpc.ClientConnInterface
}

func NewProductNetClient(cc grpc.ClientConnInterface) ProductNetClient {
	return &productNetClient{cc}
}

func (c *productNetClient) GetSwitchInfo(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchReply, error) {
	out := new(SwitchReply)
	err := c.cc.Invoke(ctx, ProductNet_GetSwitchInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productNetClient) GetControlVars(ctx context.Context, in *ControlVarRequest, opts ...grpc.CallOption) (*ControlVarReply, error) {
	out := new(ControlVarReply)
	err := c.cc.Invoke(ctx, ProductNet_GetControlVars_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productNetClient) GetControlledVars(ctx context.Context, in *ControlledVarRequest, opts ...grpc.CallOption) (*ControlledVarReply, error) {
	out := new(ControlledVarReply)
	err := c.cc.Invoke(ctx, ProductNet_GetControlledVars_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productNetClient) GetConfoundingVars(ctx context.Context, in *ConfoundingVarRequest, opts ...grpc.CallOption) (*ConfoundingVarReply, error) {
	out := new(ConfoundingVarReply)
	err := c.cc.Invoke(ctx, ProductNet_GetConfoundingVars_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productNetClient) GetCatalyst(ctx context.Context, in *CatalystRequest, opts ...grpc.CallOption) (*CatalystReply, error) {
	out := new(CatalystReply)
	err := c.cc.Invoke(ctx, ProductNet_GetCatalyst_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductNetServer is the server API for ProductNet service.
// All implementations must embed UnimplementedProductNetServer
// for forward compatibility
type ProductNetServer interface {
	GetSwitchInfo(context.Context, *SwitchRequest) (*SwitchReply, error)
	GetControlVars(context.Context, *ControlVarRequest) (*ControlVarReply, error)
	GetControlledVars(context.Context, *ControlledVarRequest) (*ControlledVarReply, error)
	GetConfoundingVars(context.Context, *ConfoundingVarRequest) (*ConfoundingVarReply, error)
	GetCatalyst(context.Context, *CatalystRequest) (*CatalystReply, error)
	mustEmbedUnimplementedProductNetServer()
}

// UnimplementedProductNetServer must be embedded to have forward compatible implementations.
type UnimplementedProductNetServer struct {
}

func (UnimplementedProductNetServer) GetSwitchInfo(context.Context, *SwitchRequest) (*SwitchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwitchInfo not implemented")
}
func (UnimplementedProductNetServer) GetControlVars(context.Context, *ControlVarRequest) (*ControlVarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControlVars not implemented")
}
func (UnimplementedProductNetServer) GetControlledVars(context.Context, *ControlledVarRequest) (*ControlledVarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControlledVars not implemented")
}
func (UnimplementedProductNetServer) GetConfoundingVars(context.Context, *ConfoundingVarRequest) (*ConfoundingVarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfoundingVars not implemented")
}
func (UnimplementedProductNetServer) GetCatalyst(context.Context, *CatalystRequest) (*CatalystReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalyst not implemented")
}
func (UnimplementedProductNetServer) mustEmbedUnimplementedProductNetServer() {}

// UnsafeProductNetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductNetServer will
// result in compilation errors.
type UnsafeProductNetServer interface {
	mustEmbedUnimplementedProductNetServer()
}

func RegisterProductNetServer(s grpc.ServiceRegistrar, srv ProductNetServer) {
	s.RegisterService(&ProductNet_ServiceDesc, srv)
}

func _ProductNet_GetSwitchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductNetServer).GetSwitchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductNet_GetSwitchInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductNetServer).GetSwitchInfo(ctx, req.(*SwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductNet_GetControlVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlVarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductNetServer).GetControlVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductNet_GetControlVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductNetServer).GetControlVars(ctx, req.(*ControlVarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductNet_GetControlledVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlledVarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductNetServer).GetControlledVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductNet_GetControlledVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductNetServer).GetControlledVars(ctx, req.(*ControlledVarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductNet_GetConfoundingVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfoundingVarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductNetServer).GetConfoundingVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductNet_GetConfoundingVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductNetServer).GetConfoundingVars(ctx, req.(*ConfoundingVarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductNet_GetCatalyst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalystRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductNetServer).GetCatalyst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductNet_GetCatalyst_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductNetServer).GetCatalyst(ctx, req.(*CatalystRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductNet_ServiceDesc is the grpc.ServiceDesc for ProductNet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductNet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.product_net.ProductNet",
	HandlerType: (*ProductNetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSwitchInfo",
			Handler:    _ProductNet_GetSwitchInfo_Handler,
		},
		{
			MethodName: "GetControlVars",
			Handler:    _ProductNet_GetControlVars_Handler,
		},
		{
			MethodName: "GetControlledVars",
			Handler:    _ProductNet_GetControlledVars_Handler,
		},
		{
			MethodName: "GetConfoundingVars",
			Handler:    _ProductNet_GetConfoundingVars_Handler,
		},
		{
			MethodName: "GetCatalyst",
			Handler:    _ProductNet_GetCatalyst_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_net/product_net.proto",
}
